"""advanced_sort

Revision ID: 1c001709fc55
Revises: dd44854aa12a
Create Date: 2025-04-26 17:01:57.140143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c001709fc55'
down_revision = 'dd44854aa12a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comment', 'approved_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comment', 'approved_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
