"""lecturer

Revision ID: 35af8468de8a
Revises: 
Create Date: 2023-05-04 14:47:15.618393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35af8468de8a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lecturer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lecturer_comment',
    sa.Column('lecturer_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_name', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('rate_general', sa.Integer(), nullable=False),
    sa.Column('rate_second', sa.Integer(), nullable=False),
    sa.Column('rate_third', sa.Integer(), nullable=False),
    sa.Column('rate_fourth', sa.Integer(), nullable=False),
    sa.Column('create_ts', sa.DateTime(), nullable=False),
    sa.Column('update_ts', sa.DateTime(), nullable=False),
    sa.Column('approve_author_id', sa.Integer(), nullable=True),
    sa.Column('approve_status', sa.Enum('APPROVED', 'DECLINED', 'PENDING', name='approvestatuses', native_enum=False), nullable=False),
    sa.Column('approve_time', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['lecturer_id'], ['lecturer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lecturer_comment')
    op.drop_table('lecturer')
    # ### end Alembic commands ###
