"""likes

Revision ID: 3c98a82bae8d
Revises: 1c001709fc55
Create Date: 2025-07-26 13:08:56.891422

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '3c98a82bae8d'
down_revision = '1c001709fc55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'comment_like',
        sa.Column('uuid', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('comment_uuid', sa.UUID(), nullable=False),
        sa.Column('like', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('edited_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ['comment_uuid'],
            ['comment.uuid'],
        ),
        sa.PrimaryKeyConstraint('uuid'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment_like')
    # ### end Alembic commands ###
