"""approved_by

Revision ID: 572423875c05
Revises: dd44854aa12a
Create Date: 2025-04-12 08:24:55.812306

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '572423875c05'
down_revision = 'dd44854aa12a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comment', 'approved_by', existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comment', 'approved_by', existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
