"""approved_by

Revision ID: 8206267a15ff
Revises: 5cf69f1026d9
Create Date: 2025-04-09 18:30:18.038265

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '8206267a15ff'
down_revision = '5cf69f1026d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('approved_by', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'approved_by')
    # ### end Alembic commands ###
