"""Add user_full_name to Comment table

Revision ID: d322e8331f91
Revises: beb11fd89531
Create Date: 2025-11-18 23:16:20.029675

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'd322e8331f91'
down_revision = 'beb11fd89531'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('user_fullname', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'user_fullname')
    # ### end Alembic commands ###
