"""small_edit_for_user_fullname

Revision ID: e3ff796adace
Revises: d322e8331f91
Create Date: 2025-11-19 22:31:52.469988

"""

# revision identifiers, used by Alembic.
revision = 'e3ff796adace'
down_revision = 'd322e8331f91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
